### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TJjega** [bipinkrish/Video-Compressor-Bot#2]
Not get compressed Output. Bot shown Error

![Bug](https://user-images.githubusercontent.com/113311399/189548278-48b7664c-5e6c-4450-9d64-e173ee02b753.jpg)

**Comment by bipinkrish** [comment]
It's because the platform where you hosted it detects the rise in CPU usage and kills the task

**Comment by TJjega** [comment]
I tried 700mb files too its working fine.. But this 40mb video shown this result

**Comment by bipinkrish** [comment]
it also can happen when the video is already in hevc codec
